config/routes.rb
Rails.application.routes.draw do
  get 'relationships/follow_user'
  get 'relationships/unfollow_user'

  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get 'notifications', to: 'notifications#index'
  get 'profiles/show'
  
  get 'browse', to: 'posts#browse', as: :browse_posts
  
  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  devise_for :users, :controllers => { registrations: 'registrations' }
  
  resources :posts do
   resources :comments
   member do
     get 'like'
     get 'unlike'
   end
  end
  
  get 'tags/:tag', to: 'posts#index', as: "tag"
  
  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
  
  root 'posts#index'
  

  

end

app/controllers/profiles_controller.rb
# https://www.devwalks.com/lets-build-instagram-with-rails-part-4-presenting-pretty-profiles/

class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :owned_profile, only: [:edit, :update]
  
  def show
     @posts = User.find_by(user_name: params[:user_name]).posts.order('created_at DESC')
  end
  
  def edit
  end
  
  def update
    if @user.update(profile_params)
      flash[:success] = 'Your profile has been updated.'
      redirect_to profile_path(@user.user_name)
    else
      @user.errors.full_messages
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end
  
private 
  
  def profile_params
    params.require(:user).permit(:avatar, :bio)
  end
  
  def owned_profile
    unless current_user == @user
      flash[:alert] = "That profile doesn't belong to you!"
      redirect_to root_path
    end
  end
  
  def set_user
    @user = User.find_by(user_name: params[:user_name])
  end
  
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def current_user_is_following(current_user_id, followed_user_id)
    relationship = Follow.find_by(follower_id: current_user_id, following_id: followed_user_id)
    return true if relationship
  end
end

app/views/profiles/edit.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-body">
      <div class="image-wrap">
        <%= simple_form_for @user, url: {action: "update"}, html: { multipart: true } do |f| %>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group text-center">
                <h4>Change your profile image:</h4>
                <div class="img-circle avatar-image">
                  <%= profile_avatar_select(@user) %>
                </div>
                <%= f.input :avatar, label: false, input_html: { onChange: 'loadFile(event)' } %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group text-center">
                <h4>Update your bio:</h4>
                <%= f.input :bio, label: false, input_html: { rows: 4 } %>
              </div>
            </div>
          </div>
          <div class="form-group text-center">
            <%= f.button :submit, 'Update Profile', class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="posts-wrapper">
  <div class="row profile-header">
    <div class="col-md-6">
      <div class="img-circle">
        <%= profile_avatar_select(@user) %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="user-name-and-follow">
        <h3 class="profile-user-name">
          <%= @user.user_name %>
        </h3>
        
        <span>
          <% if @user == current_user %>
            <%= link_to 'Edit Profile', edit_profile_path(@user.user_name), class: 'btn edit-button' %>
          <% else %>
            <% if current_user_is_following(current_user.id, @user.id) %>
              <%= link_to 'Following', unfollow_user_path, remote: true, class: 'btn unfollow-button', id: 'unfollow-button', method: :post %>
            <% else %>
              <%= link_to 'Follow', follow_user_path, remote: true, class: 'btn follow-button', id: 'follow-button', method: :post %>
            <% end %>
          <% end %>
        </span>
      </div>
      <hr>
      <div class="user-statistics">
        <p>
          <%= pluralize @user.posts.count, 'post' %> |
          <%= @user.followers.count %>
          <%= "follower".pluralize(@user.followers.count)%> |
          <%= @user.following.count %>
          <%= "following" %> 
        </p>
      </div>

      <p class="profile-bio">
        <%= @user.bio %>
      </p>

    </div>
  </div>
</div>


<% @posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>