config/routes.rb
Rails.application.routes.draw do
  get 'relationships/follow_user'
  get 'relationships/unfollow_user'

  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get 'notifications', to: 'notifications#index'
  get 'profiles/show'
  
  get 'browse', to: 'posts#browse', as: :browse_posts
  
  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  devise_for :users, :controllers => { registrations: 'registrations' }
  
  resources :posts do
   resources :comments
   member do
     get 'like'
     get 'unlike'
   end
  end
  
  get 'tags/:tag', to: 'posts#index', as: "tag"
  
  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
  
  root 'posts#index'
  

  

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  validates :user_id, :notified_by_id, :post_id, :notice_type, presence: true

  belongs_to :user
  belongs_to :notified_by, class_name: 'User'
  belongs_to :post

end

app/controllers/notifications_controller.rb
# https://www.devwalks.com/lets-build-instagram-part-6-notifications/ 

class NotificationsController < ApplicationController
  def link_through
     @notification = Notification.find(params[:id])
     @notification.update read: true
     redirect_to post_path @notification.post
  end
  
  def index
    @notifications = current_user.notifications
    
     respond_to do |format|
       format.js
       format.html
     end
  end
  
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<li class="notification_mini">
  <%= link_to "#{notification.notified_by.user_name} has left a #{notification.notice_type} on your post", link_through_path(notification) %>
  <%= time_ago_in_words(notification.created_at) + " ago" %>
</li>

app/views/notifications/_notification_dropdown.html.erb
<div class="dropdown notification-dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    <%= current_user.notifications.where(read:false).count %>
    <span class="glyphicon glyphicon-flag"></span>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
    <li class="dropdown-header text-center">Notifications</li>
      <%= render current_user.notifications.where(read: false).last(5).reverse %>
    <li class="divider" role="separator"></li>
    <li class="text-center">
      <%= link_to 'View All', notifications_path %>
    </li>
  </ul>
</div>

app/views/notifications/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <ul class="notification-index-list list-group">
        <h1 class="text-center">Your Notifications</h1>
        <%= render @notifications, selector: "long" %>
      </ul>
    </div>
  </div>
</div>

<% if current_user.notifications.length > 10 %>
  <div id="paginator", class="text-center">
    <%= link_to_next_page @notifications, 'LOAD MORE', remote: true, id: 'load_more' %>
  </div>
<% end %>

app/views/notifications/index.js.erb
$('.notification-index-list').append("<%= escape_javascript(render @notifications, selector: "long") %>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@notifications, 'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator').remove(); } 

app/views/notifications/link_through.html.erb
<h1>Notifications#link_through</h1>
<p>Find me in app/views/notifications/link_through.html.erb</p>