config/routes.rb
Rails.application.routes.draw do
  get 'relationships/follow_user'
  get 'relationships/unfollow_user'

  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get 'notifications', to: 'notifications#index'
  get 'profiles/show'
  
  get 'browse', to: 'posts#browse', as: :browse_posts
  
  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  devise_for :users, :controllers => { registrations: 'registrations' }
  
  resources :posts do
   resources :comments
   member do
     get 'like'
     get 'unlike'
   end
  end
  
  get 'tags/:tag', to: 'posts#index', as: "tag"
  
  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
  
  root 'posts#index'
  

  

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default"> 
  <div class="navbar-container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <div class="navbar-brand">
        <%= link_to(image_tag("logo_final_v3.png"), root_path) %>
      </div>
    </div>
  
    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= render 'notifications/notification_dropdown' %>
          </li>
          <li class="nav-user">
            <%= link_to current_user.user_name, profile_path(current_user.user_name) %>
          </li>
          <li>
              <%= link_to "Browse All", browse_posts_path %>
          </li>
          <li>
            <%= link_to "New Post", new_post_path %>
          </li>
          <li>
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          </li>
          <% else %>
          <li>
            <%= link_to "Login", new_user_session_path %>
          </li>
          <li>
            <%= link_to "Register", new_user_registration_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>18% Grey</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>

  <% flash.each do |name, msg| %>
  <div class="container">
    <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
    <% end %>
  </div>

<%= yield %>

</body>
</html>